# Solidity tests
sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
env:
  global:
    - SOLIDITY_COVERAGE=true
before_script:
  - truffle version
script:
  - npm run test
# notifications:
#     slack: --------
#     on_success: change
#     on_failure: always
#     on_pull_requests: false
